version: '3.9'

services:
  db:
    container_name: pgdb
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: "api"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/app
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
  
  react:
    container_name: "react"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - api


volumes:
  pgdata: {}