# Generated by Django 4.2.7 on 2023-11-02 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('document', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BLOCKED', 'Bloqueado'), ('IN_REVISION', 'Em análise'), ('LIBERATED', 'Liberado')], default='LIBERATED', max_length=15)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
                'ordering': ['name'],
            },
        ),
    ]
